- name: Install and Configure LightHouse
  hosts: lighthouse
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Clone LightHouse repository
      ansible.builtin.git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        dest: /var/www/lighthouse
        # Удалите строку version или замените 'main' на правильное название ветки
        # version: main

    - name: Ensure Nginx sites-available directory exists
      ansible.builtin.file:
        path: /etc/nginx/sites-available
        state: directory

    - name: Configure Nginx for LightHouse
      ansible.builtin.template:
        src: lighthouse.nginx.j2
        dest: /etc/nginx/sites-available/lighthouse

    - name: Ensure Nginx sites-enabled directory exists
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled
        state: directory

    - name: Enable LightHouse site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/lighthouse
        dest: /etc/nginx/sites-enabled/lighthouse
        state: link

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted







